### PR TITLE
Proton Fixes Context Menu

### PR DESCRIPTION
**Pull request by benyaminl**
Adding Proton Fixes. So it works on FF Proton 91+

### CODE REVIEW

**Comment by benyaminl** [comment]
For This Context Menu
image
And 
image

**Comment by M1ch431** [comment]
Looks good to me, thank you!

**Comment by benyaminl** [comment]
For This Context Menu
image


> 
> 
> Looks good to me, thank you!

Wait there're something still left behind :/

**Comment by M1ch431** [comment]
Oh no, I hastily merged. The fault is mine, was about to test it out.

Should I go ahead and revert in the mean time?

**Comment by benyaminl** [comment]
> 
> 
> Oh no, I hastily merged. The fault is mine, was about to test it out.
> 
> Should I go ahead and revert in the mean time?

Nono, I will add another commit hehe..

**Pull request merged**
